Bugfix: Fixed exposed

diff --git a/.github/workflows/filter-profanity.yml b/.github/workflows/filter-profanity.yml
--- a/.github/workflows/filter-profanity.yml
+++ b/.github/workflows/filter-profanity.yml
@@ -20,7 +20,8 @@ jobs:
           echo "::notice title=Safety first!::Only the actions will be review the commit messages for safety features."
 
       - name: Conditional step if commit message contains profanity
-        if: contains(env.COMMIT_MESSAGE, 'attack') || contains(env.COMMIT_MESSAGE, 'bail') || contains(env.COMMIT_MESSAGE, 'bang') || contains(env.COMMIT_MESSAGE, 'beast') || contains(env.COMMIT_MESSAGE, 'boom') || contains(env.COMMIT_MESSAGE, 'curse') || contains(env.COMMIT_MESSAGE, 'cyber') || contains(env.COMMIT_MESSAGE, 'dirt') || contains(env.COMMIT_MESSAGE, 'dope') || contains(env.COMMIT_MESSAGE, 'elect') || contains(env.COMMIT_MESSAGE, 'erect') || contains(env.COMMIT_MESSAGE, 'errap') || contains(env.COMMIT_MESSAGE, 'explod') || contains(env.COMMIT_MESSAGE, 'explos') || contains(env.COMMIT_MESSAGE, 'flirt') || contains(env.COMMIT_MESSAGE, 'fuck') || contains(env.COMMIT_MESSAGE, 'genocid') || contains(env.COMMIT_MESSAGE, 'hell') || contains(env.COMMIT_MESSAGE, 'intox') || contains(env.COMMIT_MESSAGE, 'kill') || contains(env.COMMIT_MESSAGE, 'murder') || contains(env.COMMIT_MESSAGE, 'pish') || contains(env.COMMIT_MESSAGE, 'pollut') || contains(env.COMMIT_MESSAGE, 'punch') || contains(env.COMMIT_MESSAGE, 'pvp') || contains(env.COMMIT_MESSAGE, 'refus') || contains(env.COMMIT_MESSAGE, 'riot') || contains(env.COMMIT_MESSAGE, 'sex') || contains(env.COMMIT_MESSAGE, 'suck') || contains(env.COMMIT_MESSAGE, 'troll') || contains(env.COMMIT_MESSAGE, 'violat') || contains(env.COMMIT_MESSAGE, 'violen') || contains(env.COMMIT_MESSAGE, 'violet')
         run: |
-          echo "::error title=Profanity detected!::This update can't be used on this repository. For more information how to follow these Community Standards, see https://pennyball.stynegame.de/communityguide";
-          exit 1;
+          if [[ "$COMMIT_MESSAGE" =~ (attack[^*]|bail[^*]|bang[^*]|beast[^*]|boom[^*]|b[^*]tch|bull[^*]|cr[^*]p|curse[^*]|cursi[^*]|cyber[^*]|dirt[^*]|d[^*]ke|dope|elect[^*]|erect[^*]|errap[^*]|explod[^*]|explos[^*]|expos[^*]|f[^*]ck[^*]|f[^*]ght[^*]|flirt|f[^*]rt[^*]|genocid[^*]|hell|intox[^*]|kill[^*]|murder[^*]|pish[^*]|pollut[^*]|poop|p[^*]ss[^*]|punch[^*]|pvp|refus[^*]|riot[^*]|sex|sh[^*]t|sl[^*]b|slic[^*]|sl*rp|st*b|suck[^*]|troll[^*]|violat[^*]|violen[^*]|violet[^*]) ]]; then
+            echo "::error title=Profanity detected!::This update can't be used on this repository. For more information how to follow these Community Standards, see https://pennyball.stynegame.de/communityguide";
+            exit 1;
+          fi
